# Generated by Django 3.2 on 2021-05-08 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('availability', models.BooleanField(default=False)),
                ('daytime', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_credits', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('short_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_credits', models.PositiveSmallIntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssapp.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('credits', models.PositiveSmallIntegerField()),
                ('category', models.ManyToManyField(to='ssapp.CourseCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(choices=[('Information Technology', 'IT'), ('Accounting', 'ACCT'), ('TESOL', 'TESOL'), ('Management', 'MGNT'), ('Teaching', 'TEACH'), ('Christian Studies', 'CS'), ('Bioscience', 'BIO'), ('Public Health', 'PH'), ('MedTech', 'MT'), ('English as a Second Language', 'ESL'), ('Nursing', 'NURS')], default='English as a Second Language', max_length=50)),
                ('faculty', models.CharField(choices=[('Arts & Humanities', 'FAH'), ('Business Administration', 'FBA'), ('Education', 'FED'), ('Religious Studies', 'FRS'), ('Science', 'FOS'), ('Information Technology', 'FIT'), ('Mission Faculty of Nursing', 'MFN')], default='Arts & Humanities', max_length=50)),
                ('enrolled_course', picklefield.fields.PickledObjectField(default={}, editable=False)),
                ('completed_course', picklefield.fields.PickledObjectField(default={}, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
