# Generated by Django 3.2 on 2021-05-11 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='enrolled_class',
            field=models.ManyToManyField(blank=True, to='ssapp.ClassSchedule'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
