# Generated by Django 3.2 on 2021-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('General Education Courses', 'General Education Courses'), ('Professional Courses', 'Professional Courses')], default='Professional Courses', max_length=30),
        ),
    ]
