# Generated by Django 3.2 on 2021-04-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0002_alter_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
