# Generated by Django 3.2 on 2021-05-09 03:44

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0002_auto_20210508_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='daytime',
            field=picklefield.fields.PickledObjectField(default={}, editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=False)),
                ('daytime', picklefield.fields.PickledObjectField(default={}, editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssapp.course')),
            ],
        ),
    ]
