# Generated by Django 3.2 on 2021-05-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0002_auto_20210511_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='coures',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='ssapp.Course'),
        ),
        migrations.AlterField(
            model_name='account',
            name='enrolled_class',
            field=models.ManyToManyField(blank=True, related_name='enrolled_class', to='ssapp.ClassSchedule'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
