# Generated by Django 3.2 on 2021-05-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0003_auto_20210513_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='curriculum', to='ssapp.Course'),
        ),
    ]
