# Generated by Django 3.2 on 2021-05-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0005_auto_20210504_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='account',
            name='minor',
        ),
    ]
