# Generated by Django 3.2 on 2021-05-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0005_auto_20210509_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='enrolled_course',
        ),
        migrations.AddField(
            model_name='account',
            name='enrolled_course',
            field=models.ManyToManyField(to='ssapp.Course'),
        ),
    ]
