# Generated by Django 3.2 on 2021-05-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0005_alter_classschedule_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='completed_course',
        ),
        migrations.AddField(
            model_name='account',
            name='completed_course',
            field=models.ManyToManyField(blank=True, related_name='completed_courses', to='ssapp.Course'),
        ),
    ]
