# Generated by Django 3.2 on 2021-05-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0006_auto_20210514_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='earned_credits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
