# Generated by Django 3.2 on 2021-05-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0007_account_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='faculty',
            field=models.CharField(choices=[('Arts & Humanities', 'FAH'), ('Business Administration', 'FBA'), ('Education', 'FED'), ('Religious Studies', 'FRS'), ('Science', 'FOS'), ('Information Technology', 'FIT'), ('Mission Faculty of Nursing', 'MFN')], default='Arts & Humanities', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='major',
            field=models.CharField(choices=[('Information Technology', 'IT'), ('Accounting', 'ACCT'), ('TESOL', 'TESOL'), ('Management', 'MGNT'), ('Teaching', 'TEACH'), ('Christian Studies', 'CS'), ('Bioscience', 'BIO'), ('Public Health', 'PH'), ('MedTech', 'MT'), ('English as a Second Language', 'ESL'), ('Nursing', 'NURS')], default='English as a Second Language', max_length=50),
        ),
    ]
