# Generated by Django 3.2 on 2021-05-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0008_course_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='short_name',
        ),
    ]
